// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByt3E3DtuWEjZ6jE2PdKJImMSbm9LsItI',
    appId: '1:749751614319:web:3ab287801ea4321c9f869a',
    messagingSenderId: '749751614319',
    projectId: 'vgram-6772a',
    authDomain: 'vgram-6772a.firebaseapp.com',
    storageBucket: 'vgram-6772a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgY9cI4Auf2cy1HGdUF4zlp608iSpca0',
    appId: '1:749751614319:android:cda9ba276c6ab6a79f869a',
    messagingSenderId: '749751614319',
    projectId: 'vgram-6772a',
    storageBucket: 'vgram-6772a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptIlz3PJUciIculXqrgMTftzqDF2jqJI',
    appId: '1:749751614319:ios:476f1caab56cdd5c9f869a',
    messagingSenderId: '749751614319',
    projectId: 'vgram-6772a',
    storageBucket: 'vgram-6772a.appspot.com',
    iosClientId: '749751614319-k7ubagdtbv1v2m0lq4dcrgchiq607mbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptIlz3PJUciIculXqrgMTftzqDF2jqJI',
    appId: '1:749751614319:ios:476f1caab56cdd5c9f869a',
    messagingSenderId: '749751614319',
    projectId: 'vgram-6772a',
    storageBucket: 'vgram-6772a.appspot.com',
    iosClientId: '749751614319-k7ubagdtbv1v2m0lq4dcrgchiq607mbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vgram',
  );
}
